// <auto-generated />
using IdeioMarketing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdeioMarketing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260414110714_picxe")]
    partial class picxe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IdeioMarketing.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPackageMultiSelected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubPackageMultiSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPiece")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.PackageFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<int?>("SubPackageId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("SubPackageId");

                    b.ToTable("PackageFeatures");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.PaymentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DiscountRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PaymentPlans");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.SubPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOneTime")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPiece")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Piece")
                        .HasColumnType("int");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubPackages");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Username = "admin",
                            password = "xyz123456"
                        });
                });

            modelBuilder.Entity("IdeioMarketing.Entities.Package", b =>
                {
                    b.HasOne("IdeioMarketing.Entities.Category", "Category")
                        .WithMany("Packages")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.PackageFeatures", b =>
                {
                    b.HasOne("IdeioMarketing.Entities.Package", "Package")
                        .WithMany("PackageFeatures")
                        .HasForeignKey("PackageId");

                    b.HasOne("IdeioMarketing.Entities.SubPackage", "SubPackage")
                        .WithMany("PackageFeatures")
                        .HasForeignKey("SubPackageId");

                    b.Navigation("Package");

                    b.Navigation("SubPackage");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.SubPackage", b =>
                {
                    b.HasOne("IdeioMarketing.Entities.Category", "Category")
                        .WithMany("SubPackages")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.Category", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("SubPackages");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.Package", b =>
                {
                    b.Navigation("PackageFeatures");
                });

            modelBuilder.Entity("IdeioMarketing.Entities.SubPackage", b =>
                {
                    b.Navigation("PackageFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
