<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\IdeioMarketing\MarketingFeature\Content\MarketingDatabasePersistenceHtmlEnhancement.cs" Link="Source\MarketingDatabasePersistenceHtmlEnhancement.cs" />
    <Compile Include="..\IdeioMarketing\MarketingFeature\Content\MarketingHtmlTemplate.cs" Link="Source\MarketingHtmlTemplate.cs" />
    <Compile Include="..\IdeioMarketing\MarketingFeature\Content\MarketingMobileNavigationHtmlEnhancement.cs" Link="Source\MarketingMobileNavigationHtmlEnhancement.cs" />
    <Compile Include="..\IdeioMarketing\MarketingFeature\Content\MarketingPipelineHtmlEnhancement.cs" Link="Source\MarketingPipelineHtmlEnhancement.cs" />
    <Compile Include="..\IdeioMarketing\MarketingFeature\Data\MarketingSeedData.cs" Link="Source\MarketingSeedData.cs" />
    <Compile Include="..\IdeioMarketing\MarketingFeature\Entities\*.cs" Link="Source\Entities\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
